import type { Metadata, Viewport } from 'next'
import './globals.css'
import 'sonner/dist/styles.css'

/**
 * Deployment-region locale switch — build-time inlined.
 *
 * The domestic (weave.eo2suite.cn) and international (weave.eo2suite.com)
 * sites are BUILT separately: the CN build sets NEXT_PUBLIC_DEPLOY_REGION=cn,
 * the international build sets it to `global`. next.config.mjs FAILS the
 * production build when the variable is missing or invalid, so every
 * deployment is guaranteed to carry an explicit region. Dev defaults to
 * English. Mirrors the pattern in app/help/privacy/page.tsx.
 */
const IS_CN_BUILD = process.env.NEXT_PUBLIC_DEPLOY_REGION === 'cn'

const SITE_URL = IS_CN_BUILD ? 'https://weave.eo2suite.cn' : 'https://weave.eo2suite.com'

const metadataByRegion: Metadata = IS_CN_BUILD
  ? {
      title: '怡氧知知',
      description: '面向创作者的 AI 原生工作台：本地优先的文件、知识工作流与多智能体编排',
      alternates: { canonical: SITE_URL },
      openGraph: {
        type: 'website',
        siteName: '怡氧知知',
        title: '怡氧知知 — AI 原生创作工作台',
        description: '本地优先的文件、知识工作流与多智能体编排。数据保存在用户本机，PWA 离线可用。',
        url: SITE_URL,
        locale: 'zh_CN',
      },
    }
  : {
      title: 'EO2Weave',
      description: 'AI-native creator workspace with local-first files, knowledge workflows, and multi-agent orchestration',
      alternates: { canonical: SITE_URL },
      openGraph: {
        type: 'website',
        siteName: 'EO2Weave',
        title: 'EO2Weave — AI-native creator workspace',
        description:
          'Local-first files, knowledge workflows, and multi-agent orchestration. Your data stays on your machine; PWA offline-ready.',
        url: SITE_URL,
        locale: 'en_US',
      },
    }

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // Twitter card — og:image itself is injected by the app/opengraph-image.tsx
  // file convention (region-aware via NEXT_PUBLIC_DEPLOY_REGION).
  twitter: {
    card: 'summary_large_image',
    title: IS_CN_BUILD ? '怡氧知知 — AI 原生创作工作台' : 'EO2Weave — AI-native creator workspace',
    description: IS_CN_BUILD
      ? '本地优先的文件、知识工作流与多智能体编排。数据保存在用户本机，PWA 离线可用。'
      : 'Local-first files, knowledge workflows, and multi-agent orchestration. Your data stays on your machine; PWA offline-ready.',
  },
  ...metadataByRegion,
  // manifest.webmanifest is generated by app/manifest.ts (force-static).
  // Icons live in public/icons (git-tracked; icon-192/icon-512 satisfy the
  // Chrome installability criteria → beforeinstallprompt + address-bar
  // install icon). Declaring them here stops browsers from auto-requesting
  // /favicon.ico, which does not exist (it previously fell into the legacy
  // [...path] catch-all and returned a server error).
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icons/icon-128.png', sizes: '128x128', type: 'image/png' },
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' }],
  },
}

// Viewport settings — restores the pre-Next PWA behaviour from the old
// Vite index.html: viewport-fit=cover is required for env(safe-area-inset-*)
// on notched devices (PWA standalone mode), and zoom is disabled to match
// the app-like input experience (double-tap zoom fights the editor UI).
// themeColor uses the brand primary baseline (--primary-500 = #4D9F98 in
// globals.css); the OS UI chrome (address bar / status bar) follows it.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  themeColor: '#4D9F98',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    // suppressHydrationWarning: browser extensions (e.g. the Tongyi assistant
    // plugin) inject attributes like data-redeviation-bs-uid / class
    // tongyi-design-pc onto <html> before React hydrates, which triggers a
    // dev-only attribute-mismatch warning we cannot fix app-side. This only
    // silences attribute diffs on <html> itself — child-tree mismatches
    // (the ones that indicate real bugs) still warn as usual.
    <html lang={IS_CN_BUILD ? 'zh-CN' : 'en'} suppressHydrationWarning>
      <body>
        {/* Schema.org structured data — machine-readable app identity for
            search engines and AI answer engines. Region-matched to the build. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(
              IS_CN_BUILD
                ? {
                    '@context': 'https://schema.org',
                    '@type': 'SoftwareApplication',
                    name: '怡氧知知',
                    applicationCategory: 'BusinessApplication',
                    operatingSystem: 'Web',
                    url: SITE_URL,
                    description:
                      '面向创作者的 AI 原生工作台：本地优先的文件、知识工作流与多智能体编排',
                    offers: { '@type': 'Offer', price: '0', priceCurrency: 'CNY' },
                  }
                : {
                    '@context': 'https://schema.org',
                    '@type': 'SoftwareApplication',
                    name: 'EO2Weave',
                    applicationCategory: 'BusinessApplication',
                    operatingSystem: 'Web',
                    url: SITE_URL,
                    description:
                      'AI-native creator workspace with local-first files, knowledge workflows, and multi-agent orchestration',
                    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
                  },
            ),
          }}
        />
        {/* Capture `beforeinstallprompt` before hydration — Chrome can fire it
            long before the client-only React tree mounts, and a missed event
            is gone forever (Chrome fires it once per page load). pwa/
            install-prompt.ts adopts this buffer when its controller is built. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();window.__cwInstallPromptCapture=e});",
          }}
        />
        {children}
      </body>
    </html>
  )
}
