#!/usr/bin/env node
// Main pre-commit hook that runs frontend checks.
// Invoked by the git hook generated by setup-hooks.mjs — must exit non-zero
// so a failed check blocks the commit.
// Run from repo root: node scripts/pre-commit.mjs
import { $, cd } from 'zx'
import path from 'node:path'
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(scriptDirectory, '..')

$.verbose = true

const red = (s) => `\x1b[0;31m${s}\x1b[0m`
const green = (s) => `\x1b[0;32m${s}\x1b[0m`

console.log('🔬 Running pre-commit checks...')
console.log('')

let failed = false

const webAppDir = path.join(projectRoot, 'web', 'app')
if (fs.existsSync(webAppDir)) {
  console.log('')
  console.log('⚛️  Running frontend checks...')
  cd(path.join(projectRoot, 'web'))

  // TypeScript type check
  console.log('🔍 Running TypeScript type check...')
  try {
    await $`pnpm run typecheck`
  } catch {
    console.log('')
    console.log(red('❌ TypeScript type check failed'))
    failed = true
  }

  // ESLint check (only for staged files)
  console.log('')
  console.log('🔍 Running ESLint on staged files...')
  try {
    await $`npx lint-staged`
  } catch {
    console.log('')
    console.log(red('❌ ESLint check failed'))
    failed = true
  }

  // Add back any files modified by lint-staged (only tracked files)
  console.log('')
  console.log('📝 Adding back formatted files...')
  await $`git add -u .`
}

// i18n key parity — missing locale keys fall back to the default locale at
// runtime, so dropped translations ship as silent regressions. Cheap AST
// check, so it runs unconditionally on every commit. Runs from the project
// root (the cwd above is web/, and the script lives in the root package).
console.log('')
console.log('🌍 Running i18n key parity check...')
try {
  await $`node ${path.join(projectRoot, 'scripts', 'check-i18n-parity.mjs')}`
} catch {
  console.log('')
  console.log(red('❌ i18n key parity check failed'))
  console.log('    Add the missing keys to every locale (see list above), or')
  console.log('    update the EXCEPTIONS list in scripts/check-i18n-parity.mjs')
  console.log('    if the asymmetry is intentional.')
  failed = true
}

console.log('')
if (failed) {
  console.log(red('❌ Pre-commit checks failed. Please fix the issues above.'))
  console.log('')
  console.log('Tips:')
  console.log('  - Run \'make fmt\' to format code')
  console.log('  - Run \'make lint:fix\' to fix ESLint issues')
  console.log('  - Run \'make typecheck\' to check TypeScript types')
  process.exit(1)
}

console.log(green('✅ All pre-commit checks passed!'))
