/**
 * Asset metadata — describes a file asset attached to a message.
 *
 * Assets live in the OPFS `assets/` directory and are mounted at `/mnt_assets/`
 * in Pyodide. They can be either uploaded by the user or generated by the agent.
 */

export interface AssetMeta {
  /** Unique identifier (crypto.randomUUID) */
  id: string
  /** File name (e.g. "chart.png") */
  name: string
  /** File size in bytes */
  size: number
  /** MIME type inferred from file extension */
  mimeType: string
  /** How the file entered the system */
  direction: 'upload' | 'generated'
  /** Creation timestamp (Date.now()) */
  createdAt: number
  /** OCR recognized text (only for image assets, if OCR succeeded) */
  ocrText?: string
  /** Base64-encoded image data (only for image assets, for Vision API) */
  ocrBase64?: string
}

/**
 * Snapshot entry for a single file in the assets directory.
 * Used for before/after diff to detect new or modified files.
 */
export interface FileSnapshotEntry {
  size: number
  lastModified: number
}

/** Map of filename → snapshot entry */
export type FileSnapshot = Map<string, FileSnapshotEntry>

/**
 * MIME type lookup table keyed by file extension (lowercase, no dot).
 */
const MIME_MAP: Record<string, string> = {
  // Text
  txt: 'text/plain',
  csv: 'text/csv',
  json: 'application/json',
  xml: 'application/xml',
  html: 'text/html',
  htm: 'text/html',
  md: 'text/markdown',
  css: 'text/css',
  js: 'text/javascript',
  ts: 'text/typescript',
  yaml: 'application/x-yaml',
  yml: 'application/x-yaml',
  // Images
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  svg: 'image/svg+xml',
  webp: 'image/webp',
  ico: 'image/x-icon',
  bmp: 'image/bmp',
  // Documents
  pdf: 'application/pdf',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xls: 'application/vnd.ms-excel',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  doc: 'application/msword',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  ppt: 'application/vnd.ms-powerpoint',
  // Audio
  mp3: 'audio/mpeg',
  wav: 'audio/wav',
  ogg: 'audio/ogg',
  // Video
  mp4: 'video/mp4',
  mov: 'video/quicktime',
  webm: 'video/webm',
  // Archive
  zip: 'application/zip',
  gz: 'application/gzip',
  tar: 'application/x-tar',
}

/**
 * Infer MIME type from file extension.
 * Falls back to 'application/octet-stream' for unknown extensions.
 */
export function inferMimeType(filename: string): string {
  const ext = filename.includes('.') ? filename.split('.').pop()!.toLowerCase() : ''
  return MIME_MAP[ext] || 'application/octet-stream'
}
